import React from 'react'

export default function Projects(){
  return (
    <div style={{display:'flex',flexDirection:'column',gap:12}}>
      <h1>Projects</h1>
      <div className="card-surface">
        <div className="muted">Project-based learning assignments generated by AI.</div>
        <ul style={{marginTop:8}}>
          <li>To-Do App (Beginner)</li>
          <li>REST API (Intermediate)</li>
          <li>CLI Tool (Advanced)</li>
        </ul>
      </div>
    </div>
  )
}
